wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:name>', views.entry, name='entry'),
    path('add_page', views.add_page, name='add_page'),
    path('edit_page/<str:name>', views.edit_page, name='edit_page')
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls", namespace="wiki")),
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django import forms

from . import util
import re
import markdown2
import random

entry_list = []
for entry in util.list_entries():
    entry_list.append(entry.lower())

class NewPageForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(widget=forms.Textarea)

def index(request):
    if request.method == "POST":
        name = request.POST.get('q').lower()

        entry_list_like_q = [entry.capitalize() for entry in entry_list if name in entry]
        
        if name in entry_list:
            return render(request, "encyclopedia/entry.html", {
                "title": name.capitalize(),
                "content": markdown2.markdown(util.get_entry(name)),
                "random_page": random_page()
            })

        return render(request, "encyclopedia/index.html", {
            "entries": entry_list_like_q,
            "random_page": random_page()
        })

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "random_page": random_page()
    })

def entry(request, name):
    if request.method == "POST":
        url = reverse('wiki:edit_page', kwargs={'name': name})
        return HttpResponseRedirect(url)
    return render(request, "encyclopedia/entry.html", {
        "title": name.capitalize(),
        "content": markdown2.markdown(util.get_entry(name)),
        "random_page": random_page()
    })

def edit_page(request, name):
    edit_form = NewPageForm()
    title = edit_form.fields["title"].initial = name
    content = edit_form.fields["content"].initial = util.get_entry(name)
    if request.method == "POST":
        form = NewPageForm(request.POST)
        content_updated = request.POST.get('content')
        if len(content_updated) < 10:
            print(len(content_updated))
            return render(request, 'encyclopedia/edit_page.html', {
                "edit_form": form,
                "error_message": "Content is too short",
                "title": title,
                "random_page": random_page()
            })
        util.save_entry(title, content_updated)
        url = reverse('wiki:entry', kwargs={'name': name})
        return HttpResponseRedirect(url)
    return render(request, "encyclopedia/edit_page.html", {
        "edit_form": edit_form,
        "title": title,
        "random_page": random_page()
    })

def add_page(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            if title.lower() not in entry_list:
                content = form.cleaned_data["content"]  
                util.save_entry(title, content)
                return render(request, "encyclopedia/add_page.html", {
                    "form": NewPageForm(),
                    "success_message": "Page added d-_-b",
                    "random_page": random_page()
                })
            else: 
                return render(request, "encyclopedia/add_page.html", {
                    "form": form,
                    "error_message": "Page with this title already exists.",
                    "random_page": random_page()
                })
    return render(request, "encyclopedia/add_page.html", {
        "form": NewPageForm(),
        "random_page": random_page()
    })


def random_page():
    return entry_list[random.randint(0, len(entry_list)-1)]

wiki/wiki/views.py
from django.shortcuts import render

from encyclopedia import util

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

wiki/encyclopedia/templates/encyclopedia/add_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Page creator
{% endblock %}
{% block random %}
    <a href="{% url 'wiki:entry' name=random_page %}">Random Page</a>
{% endblock %}
{% block body %}
    
    
    {% load bootstrap %}
    <form method="POST" style="max-width: 600px;">
        {% if error_message %}
            <div class="alert alert-info" role="alert" style="text-align: center;">
                {{ error_message }}
            </div>
        {% endif %}
        {% if success_message %}
            <div class="alert alert-success" role="alert" style="text-align: center;">
                {{ success_message }}
            </div>
        {% endif %}

        {% csrf_token %}
        {{ form.title | bootstrap }}
        {{ form.content | bootstrap }}
        <input class="btn btn-primary" type="submit" value="Add">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Page editor
{% endblock %}
{% block random %}
    <a href="{% url 'wiki:entry' name=random_page %}">Random Page</a>
{% endblock %}
{% block body %}
    {% load bootstrap %}
    <form method="POST" style="max-width: 600px;">
        {% if error_message %}
            <div class="alert alert-info" role="alert" style="text-align: center;">
                {{ error_message }}
            </div>
        {% endif %}
        <h1>{{ title }}</h1>
        {% csrf_token %}
        {{ edit_form.content | bootstrap }}
        <input class="btn btn-primary" type="submit" value="Add">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %} 

{% block title %} 
    {{ title }} 
{% endblock %} 
{% block random %}
    <a href="{% url 'wiki:entry' name=random_page %}">Random Page</a>
{% endblock %}
{% block body %} 
    {{ content | safe}} 
    
    <form method="POST">
        {% csrf_token %}
        <input class="btn btn-primary" type="submit" value="Edit">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}
{% block random %}
    <a href="{% url 'wiki:entry' name=random_page %}">Random Page</a>
{% endblock %}
{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry_ in entries %}
            <li><a href="{% url 'wiki:entry' name=entry_ %}">{{ entry_ }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:add_page' %}">Create New Page</a>
                </div>
                <div>
                    {% block random %}
                        
                    {% endblock %}
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>